/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.phm.mbuilds;
	
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */

public class MbuildsBodyVO extends SuperVO {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7622053515926257148L;


	private transient java.lang.String pk_builds;


	public static final String PK_BUILDS = "pk_builds";
	public static final String PK_BUILDS_B = "pk_builds_b";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_ORG_V = "pk_org_v";
	public static final String PK_DEPT = "pk_dept";
	public static final String PK_DEPT_V = "pk_dept_v";
	public static final String CMATERIALVID = "cmaterialvid";
	public static final String CMATERIALID = "cmaterialid";
	public static final String CROWNO = "crowno";
	public static final String MEMO = "memo";
	public static final String BDEF1 = "bdef1";
	public static final String BDEF2 = "bdef2";
	public static final String BDEF3 = "bdef3";
	public static final String BDEF4 = "bdef4";
	public static final String BDEF5 = "bdef5";
	public static final String BDEF6 = "bdef6";
	public static final String BDEF7 = "bdef7";
	public static final String BDEF8 = "bdef8";
	public static final String BDEF9 = "bdef9";
	public static final String BDEF10 = "bdef10";
	public static final String BDEF11 = "bdef11";
	public static final String BDEF12 = "bdef12";
	public static final String BDEF13 = "bdef13";
	public static final String BDEF14 = "bdef14";
	public static final String BDEF15 = "bdef15";
	public static final String BDEF16 = "bdef16";
	public static final String BDEF17 = "bdef17";
	public static final String BDEF18 = "bdef18";
	public static final String BDEF19 = "bdef19";
	public static final String BDEF20 = "bdef20";
	public static final String BDEF21 = "bdef21";
	public static final String BDEF22 = "bdef22";
	public static final String BDEF23 = "bdef23";
	public static final String BDEF24 = "bdef24";
	public static final String BDEF25 = "bdef25";
	public static final String BDEF26 = "bdef26";
	public static final String BDEF27 = "bdef27";
	public static final String BDEF28 = "bdef28";
	public static final String BDEF29 = "bdef29";
	public static final String BDEF30 = "bdef30";
			
	/**
	 * 属性pk_builds的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_builds () {
		return pk_builds;
	}   
	/**
	 * 属性pk_builds的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newPk_builds java.lang.String
	 */
	public void setPk_builds (java.lang.String newPk_builds ) {
		this.pk_builds = newPk_builds;
	} 	  
	/**
	 * 属性pk_builds_b的Getter方法.属性名：子实体主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_builds_b () {
		return (java.lang.String)getAttributeValue("pk_builds_b");
	}   
	/**
	 * 属性pk_builds_b的Setter方法.属性名：子实体主键
	 * 创建日期:
	 * @param newPk_builds_b java.lang.String
	 */
	public void setPk_builds_b (java.lang.String newPk_builds_b ) {
	 	setAttributeValue("pk_builds_b", newPk_builds_b);
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return (java.lang.String)getAttributeValue("pk_group");
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	setAttributeValue("pk_group", newPk_group);
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：项目组织最新版本
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return (java.lang.String)getAttributeValue("pk_org");
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：项目组织最新版本
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	setAttributeValue("pk_org", newPk_org);
	} 	  
	/**
	 * 属性pk_org_v的Getter方法.属性名：项目组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org_v () {
		return (java.lang.String)getAttributeValue("pk_org_v");
	}   
	/**
	 * 属性pk_org_v的Setter方法.属性名：项目组织
	 * 创建日期:
	 * @param newPk_org_v java.lang.String
	 */
	public void setPk_org_v (java.lang.String newPk_org_v ) {
	 	setAttributeValue("pk_org_v", newPk_org_v);
	} 	  
	/**
	 * 属性pk_dept的Getter方法.属性名：部门最新版本
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_dept () {
		return (java.lang.String)getAttributeValue("pk_dept");
	}   
	/**
	 * 属性pk_dept的Setter方法.属性名：部门最新版本
	 * 创建日期:
	 * @param newPk_dept java.lang.String
	 */
	public void setPk_dept (java.lang.String newPk_dept ) {
	 	setAttributeValue("pk_dept", newPk_dept);
	} 	  
	/**
	 * 属性pk_dept_v的Getter方法.属性名：部门
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_dept_v () {
		return (java.lang.String)getAttributeValue("pk_dept_v");
	}   
	/**
	 * 属性pk_dept_v的Setter方法.属性名：部门
	 * 创建日期:
	 * @param newPk_dept_v java.lang.String
	 */
	public void setPk_dept_v (java.lang.String newPk_dept_v ) {
	 	setAttributeValue("pk_dept_v", newPk_dept_v);
	} 	  
	/**
	 * 属性cmaterialvid的Getter方法.属性名：物料编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCmaterialvid () {
		return (java.lang.String)getAttributeValue("cmaterialvid");
	}   
	/**
	 * 属性cmaterialvid的Setter方法.属性名：物料编码
	 * 创建日期:
	 * @param newCmaterialvid java.lang.String
	 */
	public void setCmaterialvid (java.lang.String newCmaterialvid ) {
	 	setAttributeValue("cmaterialvid", newCmaterialvid);
	} 	  
	/**
	 * 属性cmaterialid的Getter方法.属性名：物料最新版本
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCmaterialid () {
		return (java.lang.String)getAttributeValue("cmaterialid");
	}   
	/**
	 * 属性cmaterialid的Setter方法.属性名：物料最新版本
	 * 创建日期:
	 * @param newCmaterialid java.lang.String
	 */
	public void setCmaterialid (java.lang.String newCmaterialid ) {
	 	setAttributeValue("cmaterialid", newCmaterialid);
	} 	  
	/**
	 * 属性crowno的Getter方法.属性名：行号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCrowno () {
		return (java.lang.String)getAttributeValue("crowno");
	}   
	/**
	 * 属性crowno的Setter方法.属性名：行号
	 * 创建日期:
	 * @param newCrowno java.lang.String
	 */
	public void setCrowno (java.lang.String newCrowno ) {
	 	setAttributeValue("crowno", newCrowno);
	} 	  
	/**
	 * 属性memo的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMemo () {
		return (java.lang.String)getAttributeValue("memo");
	}   
	/**
	 * 属性memo的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newMemo java.lang.String
	 */
	public void setMemo (java.lang.String newMemo ) {
	 	setAttributeValue("memo", newMemo);
	} 	  
	/**
	 * 属性bdef1的Getter方法.属性名：自定义项1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef1 () {
		return (java.lang.String)getAttributeValue("bdef1");
	}   
	/**
	 * 属性bdef1的Setter方法.属性名：自定义项1
	 * 创建日期:
	 * @param newBdef1 java.lang.String
	 */
	public void setBdef1 (java.lang.String newBdef1 ) {
	 	setAttributeValue("bdef1", newBdef1);
	} 	  
	/**
	 * 属性bdef2的Getter方法.属性名：自定义项2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef2 () {
		return (java.lang.String)getAttributeValue("bdef2");
	}   
	/**
	 * 属性bdef2的Setter方法.属性名：自定义项2
	 * 创建日期:
	 * @param newBdef2 java.lang.String
	 */
	public void setBdef2 (java.lang.String newBdef2 ) {
	 	setAttributeValue("bdef2", newBdef2);
	} 	  
	/**
	 * 属性bdef3的Getter方法.属性名：自定义项3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef3 () {
		return (java.lang.String)getAttributeValue("bdef3");
	}   
	/**
	 * 属性bdef3的Setter方法.属性名：自定义项3
	 * 创建日期:
	 * @param newBdef3 java.lang.String
	 */
	public void setBdef3 (java.lang.String newBdef3 ) {
	 	setAttributeValue("bdef3", newBdef3);
	} 	  
	/**
	 * 属性bdef4的Getter方法.属性名：自定义项4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef4 () {
		return (java.lang.String)getAttributeValue("bdef4");
	}   
	/**
	 * 属性bdef4的Setter方法.属性名：自定义项4
	 * 创建日期:
	 * @param newBdef4 java.lang.String
	 */
	public void setBdef4 (java.lang.String newBdef4 ) {
	 	setAttributeValue("bdef4", newBdef4);
	} 	  
	/**
	 * 属性bdef5的Getter方法.属性名：自定义项5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef5 () {
		return (java.lang.String)getAttributeValue("bdef5");
	}   
	/**
	 * 属性bdef5的Setter方法.属性名：自定义项5
	 * 创建日期:
	 * @param newBdef5 java.lang.String
	 */
	public void setBdef5 (java.lang.String newBdef5 ) {
	 	setAttributeValue("bdef5", newBdef5);
	} 	  
	/**
	 * 属性bdef6的Getter方法.属性名：自定义项6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef6 () {
		return (java.lang.String)getAttributeValue("bdef6");
	}   
	/**
	 * 属性bdef6的Setter方法.属性名：自定义项6
	 * 创建日期:
	 * @param newBdef6 java.lang.String
	 */
	public void setBdef6 (java.lang.String newBdef6 ) {
	 	setAttributeValue("bdef6", newBdef6);
	} 	  
	/**
	 * 属性bdef7的Getter方法.属性名：自定义项7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef7 () {
		return (java.lang.String)getAttributeValue("bdef7");
	}   
	/**
	 * 属性bdef7的Setter方法.属性名：自定义项7
	 * 创建日期:
	 * @param newBdef7 java.lang.String
	 */
	public void setBdef7 (java.lang.String newBdef7 ) {
	 	setAttributeValue("bdef7", newBdef7);
	} 	  
	/**
	 * 属性bdef8的Getter方法.属性名：自定义项8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef8 () {
		return (java.lang.String)getAttributeValue("bdef8");
	}   
	/**
	 * 属性bdef8的Setter方法.属性名：自定义项8
	 * 创建日期:
	 * @param newBdef8 java.lang.String
	 */
	public void setBdef8 (java.lang.String newBdef8 ) {
	 	setAttributeValue("bdef8", newBdef8);
	} 	  
	/**
	 * 属性bdef9的Getter方法.属性名：自定义项9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef9 () {
		return (java.lang.String)getAttributeValue("bdef9");
	}   
	/**
	 * 属性bdef9的Setter方法.属性名：自定义项9
	 * 创建日期:
	 * @param newBdef9 java.lang.String
	 */
	public void setBdef9 (java.lang.String newBdef9 ) {
	 	setAttributeValue("bdef9", newBdef9);
	} 	  
	/**
	 * 属性bdef10的Getter方法.属性名：自定义项10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef10 () {
		return (java.lang.String)getAttributeValue("bdef10");
	}   
	/**
	 * 属性bdef10的Setter方法.属性名：自定义项10
	 * 创建日期:
	 * @param newBdef10 java.lang.String
	 */
	public void setBdef10 (java.lang.String newBdef10 ) {
	 	setAttributeValue("bdef10", newBdef10);
	} 	  
	/**
	 * 属性bdef11的Getter方法.属性名：自定义项11
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef11 () {
		return (java.lang.String)getAttributeValue("bdef11");
	}   
	/**
	 * 属性bdef11的Setter方法.属性名：自定义项11
	 * 创建日期:
	 * @param newBdef11 java.lang.String
	 */
	public void setBdef11 (java.lang.String newBdef11 ) {
	 	setAttributeValue("bdef11", newBdef11);
	} 	  
	/**
	 * 属性bdef12的Getter方法.属性名：自定义项12
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef12 () {
		return (java.lang.String)getAttributeValue("bdef12");
	}   
	/**
	 * 属性bdef12的Setter方法.属性名：自定义项12
	 * 创建日期:
	 * @param newBdef12 java.lang.String
	 */
	public void setBdef12 (java.lang.String newBdef12 ) {
	 	setAttributeValue("bdef12", newBdef12);
	} 	  
	/**
	 * 属性bdef13的Getter方法.属性名：自定义项13
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef13 () {
		return (java.lang.String)getAttributeValue("bdef13");
	}   
	/**
	 * 属性bdef13的Setter方法.属性名：自定义项13
	 * 创建日期:
	 * @param newBdef13 java.lang.String
	 */
	public void setBdef13 (java.lang.String newBdef13 ) {
	 	setAttributeValue("bdef13", newBdef13);
	} 	  
	/**
	 * 属性bdef14的Getter方法.属性名：自定义项14
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef14 () {
		return (java.lang.String)getAttributeValue("bdef14");
	}   
	/**
	 * 属性bdef14的Setter方法.属性名：自定义项14
	 * 创建日期:
	 * @param newBdef14 java.lang.String
	 */
	public void setBdef14 (java.lang.String newBdef14 ) {
	 	setAttributeValue("bdef14", newBdef14);
	} 	  
	/**
	 * 属性bdef15的Getter方法.属性名：自定义项15
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef15 () {
		return (java.lang.String)getAttributeValue("bdef15");
	}   
	/**
	 * 属性bdef15的Setter方法.属性名：自定义项15
	 * 创建日期:
	 * @param newBdef15 java.lang.String
	 */
	public void setBdef15 (java.lang.String newBdef15 ) {
	 	setAttributeValue("bdef15", newBdef15);
	} 	  
	/**
	 * 属性bdef16的Getter方法.属性名：自定义项16
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef16 () {
		return (java.lang.String)getAttributeValue("bdef16");
	}   
	/**
	 * 属性bdef16的Setter方法.属性名：自定义项16
	 * 创建日期:
	 * @param newBdef16 java.lang.String
	 */
	public void setBdef16 (java.lang.String newBdef16 ) {
	 	setAttributeValue("bdef16", newBdef16);
	} 	  
	/**
	 * 属性bdef17的Getter方法.属性名：自定义项17
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef17 () {
		return (java.lang.String)getAttributeValue("bdef17");
	}   
	/**
	 * 属性bdef17的Setter方法.属性名：自定义项17
	 * 创建日期:
	 * @param newBdef17 java.lang.String
	 */
	public void setBdef17 (java.lang.String newBdef17 ) {
	 	setAttributeValue("bdef17", newBdef17);
	} 	  
	/**
	 * 属性bdef18的Getter方法.属性名：自定义项18
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef18 () {
		return (java.lang.String)getAttributeValue("bdef18");
	}   
	/**
	 * 属性bdef18的Setter方法.属性名：自定义项18
	 * 创建日期:
	 * @param newBdef18 java.lang.String
	 */
	public void setBdef18 (java.lang.String newBdef18 ) {
	 	setAttributeValue("bdef18", newBdef18);
	} 	  
	/**
	 * 属性bdef19的Getter方法.属性名：自定义项19
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef19 () {
		return (java.lang.String)getAttributeValue("bdef19");
	}   
	/**
	 * 属性bdef19的Setter方法.属性名：自定义项19
	 * 创建日期:
	 * @param newBdef19 java.lang.String
	 */
	public void setBdef19 (java.lang.String newBdef19 ) {
	 	setAttributeValue("bdef19", newBdef19);
	} 	  
	/**
	 * 属性bdef20的Getter方法.属性名：自定义项20
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef20 () {
		return (java.lang.String)getAttributeValue("bdef20");
	}   
	/**
	 * 属性bdef20的Setter方法.属性名：自定义项20
	 * 创建日期:
	 * @param newBdef20 java.lang.String
	 */
	public void setBdef20 (java.lang.String newBdef20 ) {
	 	setAttributeValue("bdef20", newBdef20);
	} 	  
	/**
	 * 属性bdef21的Getter方法.属性名：自定义项21
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef21 () {
		return (java.lang.String)getAttributeValue("bdef21");
	}   
	/**
	 * 属性bdef21的Setter方法.属性名：自定义项21
	 * 创建日期:
	 * @param newBdef21 java.lang.String
	 */
	public void setBdef21 (java.lang.String newBdef21 ) {
	 	setAttributeValue("bdef21", newBdef21);
	} 	  
	/**
	 * 属性bdef22的Getter方法.属性名：自定义项22
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef22 () {
		return (java.lang.String)getAttributeValue("bdef22");
	}   
	/**
	 * 属性bdef22的Setter方法.属性名：自定义项22
	 * 创建日期:
	 * @param newBdef22 java.lang.String
	 */
	public void setBdef22 (java.lang.String newBdef22 ) {
	 	setAttributeValue("bdef22", newBdef22);
	} 	  
	/**
	 * 属性bdef23的Getter方法.属性名：自定义项23
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef23 () {
		return (java.lang.String)getAttributeValue("bdef23");
	}   
	/**
	 * 属性bdef23的Setter方法.属性名：自定义项23
	 * 创建日期:
	 * @param newBdef23 java.lang.String
	 */
	public void setBdef23 (java.lang.String newBdef23 ) {
	 	setAttributeValue("bdef23", newBdef23);
	} 	  
	/**
	 * 属性bdef24的Getter方法.属性名：自定义项24
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef24 () {
		return (java.lang.String)getAttributeValue("bdef24");
	}   
	/**
	 * 属性bdef24的Setter方法.属性名：自定义项24
	 * 创建日期:
	 * @param newBdef24 java.lang.String
	 */
	public void setBdef24 (java.lang.String newBdef24 ) {
	 	setAttributeValue("bdef24", newBdef24);
	} 	  
	/**
	 * 属性bdef25的Getter方法.属性名：自定义项25
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef25 () {
		return (java.lang.String)getAttributeValue("bdef25");
	}   
	/**
	 * 属性bdef25的Setter方法.属性名：自定义项25
	 * 创建日期:
	 * @param newBdef25 java.lang.String
	 */
	public void setBdef25 (java.lang.String newBdef25 ) {
	 	setAttributeValue("bdef25", newBdef25);
	} 	  
	/**
	 * 属性bdef26的Getter方法.属性名：自定义项26
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef26 () {
		return (java.lang.String)getAttributeValue("bdef26");
	}   
	/**
	 * 属性bdef26的Setter方法.属性名：自定义项26
	 * 创建日期:
	 * @param newBdef26 java.lang.String
	 */
	public void setBdef26 (java.lang.String newBdef26 ) {
	 	setAttributeValue("bdef26", newBdef26);
	} 	  
	/**
	 * 属性bdef27的Getter方法.属性名：自定义项27
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef27 () {
		return (java.lang.String)getAttributeValue("bdef27");
	}   
	/**
	 * 属性bdef27的Setter方法.属性名：自定义项27
	 * 创建日期:
	 * @param newBdef27 java.lang.String
	 */
	public void setBdef27 (java.lang.String newBdef27 ) {
	 	setAttributeValue("bdef27", newBdef27);
	} 	  
	/**
	 * 属性bdef28的Getter方法.属性名：自定义项28
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef28 () {
		return (java.lang.String)getAttributeValue("bdef28");
	}   
	/**
	 * 属性bdef28的Setter方法.属性名：自定义项28
	 * 创建日期:
	 * @param newBdef28 java.lang.String
	 */
	public void setBdef28 (java.lang.String newBdef28 ) {
	 	setAttributeValue("bdef28", newBdef28);
	} 	  
	/**
	 * 属性bdef29的Getter方法.属性名：自定义项29
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef29 () {
		return (java.lang.String)getAttributeValue("bdef29");
	}   
	/**
	 * 属性bdef29的Setter方法.属性名：自定义项29
	 * 创建日期:
	 * @param newBdef29 java.lang.String
	 */
	public void setBdef29 (java.lang.String newBdef29 ) {
	 	setAttributeValue("bdef29", newBdef29);
	} 	  
	/**
	 * 属性bdef30的Getter方法.属性名：自定义项30
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBdef30 () {
		return (java.lang.String)getAttributeValue("bdef30");
	}   
	/**
	 * 属性bdef30的Setter方法.属性名：自定义项30
	 * 创建日期:
	 * @param newBdef30 java.lang.String
	 */
	public void setBdef30 (java.lang.String newBdef30 ) {
	 	setAttributeValue("bdef30", newBdef30);
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return (java.lang.Integer)getAttributeValue("dr");
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	setAttributeValue("dr", newDr);
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return (nc.vo.pub.lang.UFDateTime)getAttributeValue("ts");
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	setAttributeValue("ts", newTs);
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_builds";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_builds_b";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "pm_mbuilds_b";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public MbuildsBodyVO() {
		super();	
	}  
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.phm.mbuilds.MbuildsBodyVO" )
	public IVOMeta getMetaData() {
    	IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("phm.mbuilds_b");
   		return meta;
  	}
} 
