/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.phm.mbuilds;
	
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
public class MbuildsHeadVO extends SuperVO {


	/**
	 * 
	 */
	private static final long serialVersionUID = -2405347024763875589L;
	public static final String PK_BUILDS = "pk_builds";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_ORG_V = "pk_org_v";
	public static final String VBILLCODE = "vbillcode";
	public static final String BUSITYPE = "busitype";
	public static final String PK_BILLTYPECODE = "pk_billtypecode";
	public static final String PK_BILLTYPEID = "pk_billtypeid";
	public static final String VTRANTYPECODE = "vtrantypecode";
	public static final String CTRANTYPEID = "ctrantypeid";
	public static final String FSTATUSFLAG = "fstatusflag";
	public static final String BILLMAKER = "billmaker";
	public static final String BILLMAKETIME = "billmaketime";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String AUDITOR = "auditor";
	public static final String AUDITTIME = "audittime";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String VNOTE = "vnote";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
	public static final String DEF11 = "def11";
	public static final String DEF12 = "def12";
	public static final String DEF13 = "def13";
	public static final String DEF14 = "def14";
	public static final String DEF15 = "def15";
	public static final String DEF16 = "def16";
	public static final String DEF17 = "def17";
	public static final String DEF18 = "def18";
	public static final String DEF19 = "def19";
	public static final String DEF20 = "def20";
	public static final String DEF21 = "def21";
	public static final String DEF22 = "def22";
	public static final String DEF23 = "def23";
	public static final String DEF24 = "def24";
	public static final String DEF25 = "def25";
	public static final String DEF26 = "def26";
	public static final String DEF27 = "def27";
	public static final String DEF28 = "def28";
	public static final String DEF29 = "def29";
	public static final String DEF30 = "def30";
			
	/**
	 * 属性pk_builds的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_builds () {
		return (java.lang.String)getAttributeValue("pk_builds");
	}   
	/**
	 * 属性pk_builds的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_builds java.lang.String
	 */
	public void setPk_builds (java.lang.String newPk_builds ) {
	 	setAttributeValue("pk_builds", newPk_builds);
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return (java.lang.String)getAttributeValue("pk_group");
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	setAttributeValue("pk_group", newPk_group);
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：组织版本
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return (java.lang.String)getAttributeValue("pk_org");
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织版本
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	setAttributeValue("pk_org", newPk_org);
	} 	  
	/**
	 * 属性pk_org_v的Getter方法.属性名：组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org_v () {
		return (java.lang.String)getAttributeValue("pk_org_v");
	}   
	/**
	 * 属性pk_org_v的Setter方法.属性名：组织
	 * 创建日期:
	 * @param newPk_org_v java.lang.String
	 */
	public void setPk_org_v (java.lang.String newPk_org_v ) {
	 	setAttributeValue("pk_org_v", newPk_org_v);
	} 	  
	/**
	 * 属性vbillcode的Getter方法.属性名：单据号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVbillcode () {
		return (java.lang.String)getAttributeValue("vbillcode");
	}   
	/**
	 * 属性vbillcode的Setter方法.属性名：单据号
	 * 创建日期:
	 * @param newVbillcode java.lang.String
	 */
	public void setVbillcode (java.lang.String newVbillcode ) {
	 	setAttributeValue("vbillcode", newVbillcode);
	} 	  
	/**
	 * 属性busitype的Getter方法.属性名：业务类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBusitype () {
		return (java.lang.String)getAttributeValue("busitype");
	}   
	/**
	 * 属性busitype的Setter方法.属性名：业务类型
	 * 创建日期:
	 * @param newBusitype java.lang.String
	 */
	public void setBusitype (java.lang.String newBusitype ) {
	 	setAttributeValue("busitype", newBusitype);
	} 	  
	/**
	 * 属性pk_billtypecode的Getter方法.属性名：单据类型编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billtypecode () {
		return (java.lang.String)getAttributeValue("pk_billtypecode");
	}   
	/**
	 * 属性pk_billtypecode的Setter方法.属性名：单据类型编码
	 * 创建日期:
	 * @param newPk_billtypecode java.lang.String
	 */
	public void setPk_billtypecode (java.lang.String newPk_billtypecode ) {
	 	setAttributeValue("pk_billtypecode", newPk_billtypecode);
	} 	  
	/**
	 * 属性pk_billtypeid的Getter方法.属性名：单据类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billtypeid () {
		return (java.lang.String)getAttributeValue("pk_billtypeid");
	}   
	/**
	 * 属性pk_billtypeid的Setter方法.属性名：单据类型
	 * 创建日期:
	 * @param newPk_billtypeid java.lang.String
	 */
	public void setPk_billtypeid (java.lang.String newPk_billtypeid ) {
	 	setAttributeValue("pk_billtypeid", newPk_billtypeid);
	} 	  
	/**
	 * 属性vtrantypecode的Getter方法.属性名：交易类型编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVtrantypecode () {
		return (java.lang.String)getAttributeValue("vtrantypecode");
	}   
	/**
	 * 属性vtrantypecode的Setter方法.属性名：交易类型编码
	 * 创建日期:
	 * @param newVtrantypecode java.lang.String
	 */
	public void setVtrantypecode (java.lang.String newVtrantypecode ) {
	 	setAttributeValue("vtrantypecode", newVtrantypecode);
	} 	  
	/**
	 * 属性ctrantypeid的Getter方法.属性名：交易类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCtrantypeid () {
		return (java.lang.String)getAttributeValue("ctrantypeid");
	}   
	/**
	 * 属性ctrantypeid的Setter方法.属性名：交易类型
	 * 创建日期:
	 * @param newCtrantypeid java.lang.String
	 */
	public void setCtrantypeid (java.lang.String newCtrantypeid ) {
	 	setAttributeValue("ctrantypeid", newCtrantypeid);
	} 	  
	/**
	 * 属性fstatusflag的Getter方法.属性名：单据状态
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getFstatusflag () {
		return (java.lang.Integer)getAttributeValue("fstatusflag");
	}   
	/**
	 * 属性fstatusflag的Setter方法.属性名：单据状态
	 * 创建日期:
	 * @param newFstatusflag java.lang.Integer
	 */
	public void setFstatusflag (java.lang.Integer newFstatusflag ) {
	 	setAttributeValue("fstatusflag", newFstatusflag);
	} 	  
	/**
	 * 属性billmaker的Getter方法.属性名：制单人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getBillmaker () {
		return (java.lang.String)getAttributeValue("billmaker");
	}   
	/**
	 * 属性billmaker的Setter方法.属性名：制单人
	 * 创建日期:
	 * @param newBillmaker java.lang.String
	 */
	public void setBillmaker (java.lang.String newBillmaker ) {
	 	setAttributeValue("billmaker", newBillmaker);
	} 	  
	/**
	 * 属性billmaketime的Getter方法.属性名：制单日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getBillmaketime () {
		return (nc.vo.pub.lang.UFDate)getAttributeValue("billmaketime");
	}   
	/**
	 * 属性billmaketime的Setter方法.属性名：制单日期
	 * 创建日期:
	 * @param newBillmaketime nc.vo.pub.lang.UFDate
	 */
	public void setBillmaketime (nc.vo.pub.lang.UFDate newBillmaketime ) {
	 	setAttributeValue("billmaketime", newBillmaketime);
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：创建人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return (java.lang.String)getAttributeValue("creator");
	}   
	/**
	 * 属性creator的Setter方法.属性名：创建人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	setAttributeValue("creator", newCreator);
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return (nc.vo.pub.lang.UFDateTime)getAttributeValue("creationtime");
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	setAttributeValue("creationtime", newCreationtime);
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return (java.lang.String)getAttributeValue("modifier");
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	setAttributeValue("modifier", newModifier);
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return (nc.vo.pub.lang.UFDateTime)getAttributeValue("modifiedtime");
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	setAttributeValue("modifiedtime", newModifiedtime);
	} 	  
	/**
	 * 属性auditor的Getter方法.属性名：审批人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getAuditor () {
		return (java.lang.String)getAttributeValue("auditor");
	}   
	/**
	 * 属性auditor的Setter方法.属性名：审批人
	 * 创建日期:
	 * @param newAuditor java.lang.String
	 */
	public void setAuditor (java.lang.String newAuditor ) {
	 	setAttributeValue("auditor", newAuditor);
	} 	  
	/**
	 * 属性audittime的Getter方法.属性名：审批日期
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getAudittime () {
		return (nc.vo.pub.lang.UFDate)getAttributeValue("audittime");
	}   
	/**
	 * 属性audittime的Setter方法.属性名：审批日期
	 * 创建日期:
	 * @param newAudittime nc.vo.pub.lang.UFDate
	 */
	public void setAudittime (nc.vo.pub.lang.UFDate newAudittime ) {
	 	setAttributeValue("audittime", newAudittime);
	} 	  
	/**
	 * 属性vapprovenote的Getter方法.属性名：审批意见
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVapprovenote () {
		return (java.lang.String)getAttributeValue("vapprovenote");
	}   
	/**
	 * 属性vapprovenote的Setter方法.属性名：审批意见
	 * 创建日期:
	 * @param newVapprovenote java.lang.String
	 */
	public void setVapprovenote (java.lang.String newVapprovenote ) {
	 	setAttributeValue("vapprovenote", newVapprovenote);
	} 	  
	/**
	 * 属性vnote的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getVnote () {
		return (java.lang.String)getAttributeValue("vnote");
	}   
	/**
	 * 属性vnote的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newVnote java.lang.String
	 */
	public void setVnote (java.lang.String newVnote ) {
	 	setAttributeValue("vnote", newVnote);
	} 	  
	/**
	 * 属性def1的Getter方法.属性名：自定义项1
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef1 () {
		return (java.lang.String)getAttributeValue("def1");
	}   
	/**
	 * 属性def1的Setter方法.属性名：自定义项1
	 * 创建日期:
	 * @param newDef1 java.lang.String
	 */
	public void setDef1 (java.lang.String newDef1 ) {
	 	setAttributeValue("def1", newDef1);
	} 	  
	/**
	 * 属性def2的Getter方法.属性名：自定义项2
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef2 () {
		return (java.lang.String)getAttributeValue("def2");
	}   
	/**
	 * 属性def2的Setter方法.属性名：自定义项2
	 * 创建日期:
	 * @param newDef2 java.lang.String
	 */
	public void setDef2 (java.lang.String newDef2 ) {
	 	setAttributeValue("def2", newDef2);
	} 	  
	/**
	 * 属性def3的Getter方法.属性名：自定义项3
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef3 () {
		return (java.lang.String)getAttributeValue("def3");
	}   
	/**
	 * 属性def3的Setter方法.属性名：自定义项3
	 * 创建日期:
	 * @param newDef3 java.lang.String
	 */
	public void setDef3 (java.lang.String newDef3 ) {
	 	setAttributeValue("def3", newDef3);
	} 	  
	/**
	 * 属性def4的Getter方法.属性名：自定义项4
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef4 () {
		return (java.lang.String)getAttributeValue("def4");
	}   
	/**
	 * 属性def4的Setter方法.属性名：自定义项4
	 * 创建日期:
	 * @param newDef4 java.lang.String
	 */
	public void setDef4 (java.lang.String newDef4 ) {
	 	setAttributeValue("def4", newDef4);
	} 	  
	/**
	 * 属性def5的Getter方法.属性名：自定义项5
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef5 () {
		return (java.lang.String)getAttributeValue("def5");
	}   
	/**
	 * 属性def5的Setter方法.属性名：自定义项5
	 * 创建日期:
	 * @param newDef5 java.lang.String
	 */
	public void setDef5 (java.lang.String newDef5 ) {
	 	setAttributeValue("def5", newDef5);
	} 	  
	/**
	 * 属性def6的Getter方法.属性名：自定义项6
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef6 () {
		return (java.lang.String)getAttributeValue("def6");
	}   
	/**
	 * 属性def6的Setter方法.属性名：自定义项6
	 * 创建日期:
	 * @param newDef6 java.lang.String
	 */
	public void setDef6 (java.lang.String newDef6 ) {
	 	setAttributeValue("def6", newDef6);
	} 	  
	/**
	 * 属性def7的Getter方法.属性名：自定义项7
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef7 () {
		return (java.lang.String)getAttributeValue("def7");
	}   
	/**
	 * 属性def7的Setter方法.属性名：自定义项7
	 * 创建日期:
	 * @param newDef7 java.lang.String
	 */
	public void setDef7 (java.lang.String newDef7 ) {
	 	setAttributeValue("def7", newDef7);
	} 	  
	/**
	 * 属性def8的Getter方法.属性名：自定义项8
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef8 () {
		return (java.lang.String)getAttributeValue("def8");
	}   
	/**
	 * 属性def8的Setter方法.属性名：自定义项8
	 * 创建日期:
	 * @param newDef8 java.lang.String
	 */
	public void setDef8 (java.lang.String newDef8 ) {
	 	setAttributeValue("def8", newDef8);
	} 	  
	/**
	 * 属性def9的Getter方法.属性名：自定义项9
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef9 () {
		return (java.lang.String)getAttributeValue("def9");
	}   
	/**
	 * 属性def9的Setter方法.属性名：自定义项9
	 * 创建日期:
	 * @param newDef9 java.lang.String
	 */
	public void setDef9 (java.lang.String newDef9 ) {
	 	setAttributeValue("def9", newDef9);
	} 	  
	/**
	 * 属性def10的Getter方法.属性名：自定义项10
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef10 () {
		return (java.lang.String)getAttributeValue("def10");
	}   
	/**
	 * 属性def10的Setter方法.属性名：自定义项10
	 * 创建日期:
	 * @param newDef10 java.lang.String
	 */
	public void setDef10 (java.lang.String newDef10 ) {
	 	setAttributeValue("def10", newDef10);
	} 	  
	/**
	 * 属性def11的Getter方法.属性名：自定义项11
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef11 () {
		return (java.lang.String)getAttributeValue("def11");
	}   
	/**
	 * 属性def11的Setter方法.属性名：自定义项11
	 * 创建日期:
	 * @param newDef11 java.lang.String
	 */
	public void setDef11 (java.lang.String newDef11 ) {
	 	setAttributeValue("def11", newDef11);
	} 	  
	/**
	 * 属性def12的Getter方法.属性名：自定义项12
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef12 () {
		return (java.lang.String)getAttributeValue("def12");
	}   
	/**
	 * 属性def12的Setter方法.属性名：自定义项12
	 * 创建日期:
	 * @param newDef12 java.lang.String
	 */
	public void setDef12 (java.lang.String newDef12 ) {
	 	setAttributeValue("def12", newDef12);
	} 	  
	/**
	 * 属性def13的Getter方法.属性名：自定义项13
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef13 () {
		return (java.lang.String)getAttributeValue("def13");
	}   
	/**
	 * 属性def13的Setter方法.属性名：自定义项13
	 * 创建日期:
	 * @param newDef13 java.lang.String
	 */
	public void setDef13 (java.lang.String newDef13 ) {
	 	setAttributeValue("def13", newDef13);
	} 	  
	/**
	 * 属性def14的Getter方法.属性名：自定义项14
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef14 () {
		return (java.lang.String)getAttributeValue("def14");
	}   
	/**
	 * 属性def14的Setter方法.属性名：自定义项14
	 * 创建日期:
	 * @param newDef14 java.lang.String
	 */
	public void setDef14 (java.lang.String newDef14 ) {
	 	setAttributeValue("def14", newDef14);
	} 	  
	/**
	 * 属性def15的Getter方法.属性名：自定义项15
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef15 () {
		return (java.lang.String)getAttributeValue("def15");
	}   
	/**
	 * 属性def15的Setter方法.属性名：自定义项15
	 * 创建日期:
	 * @param newDef15 java.lang.String
	 */
	public void setDef15 (java.lang.String newDef15 ) {
	 	setAttributeValue("def15", newDef15);
	} 	  
	/**
	 * 属性def16的Getter方法.属性名：自定义项16
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef16 () {
		return (java.lang.String)getAttributeValue("def16");
	}   
	/**
	 * 属性def16的Setter方法.属性名：自定义项16
	 * 创建日期:
	 * @param newDef16 java.lang.String
	 */
	public void setDef16 (java.lang.String newDef16 ) {
	 	setAttributeValue("def16", newDef16);
	} 	  
	/**
	 * 属性def17的Getter方法.属性名：自定义项17
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef17 () {
		return (java.lang.String)getAttributeValue("def17");
	}   
	/**
	 * 属性def17的Setter方法.属性名：自定义项17
	 * 创建日期:
	 * @param newDef17 java.lang.String
	 */
	public void setDef17 (java.lang.String newDef17 ) {
	 	setAttributeValue("def17", newDef17);
	} 	  
	/**
	 * 属性def18的Getter方法.属性名：自定义项18
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef18 () {
		return (java.lang.String)getAttributeValue("def18");
	}   
	/**
	 * 属性def18的Setter方法.属性名：自定义项18
	 * 创建日期:
	 * @param newDef18 java.lang.String
	 */
	public void setDef18 (java.lang.String newDef18 ) {
	 	setAttributeValue("def18", newDef18);
	} 	  
	/**
	 * 属性def19的Getter方法.属性名：自定义项19
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef19 () {
		return (java.lang.String)getAttributeValue("def19");
	}   
	/**
	 * 属性def19的Setter方法.属性名：自定义项19
	 * 创建日期:
	 * @param newDef19 java.lang.String
	 */
	public void setDef19 (java.lang.String newDef19 ) {
	 	setAttributeValue("def19", newDef19);
	} 	  
	/**
	 * 属性def20的Getter方法.属性名：自定义项20
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef20 () {
		return (java.lang.String)getAttributeValue("def20");
	}   
	/**
	 * 属性def20的Setter方法.属性名：自定义项20
	 * 创建日期:
	 * @param newDef20 java.lang.String
	 */
	public void setDef20 (java.lang.String newDef20 ) {
	 	setAttributeValue("def20", newDef20);
	} 	  
	/**
	 * 属性def21的Getter方法.属性名：自定义项21
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef21 () {
		return (java.lang.String)getAttributeValue("def21");
	}   
	/**
	 * 属性def21的Setter方法.属性名：自定义项21
	 * 创建日期:
	 * @param newDef21 java.lang.String
	 */
	public void setDef21 (java.lang.String newDef21 ) {
	 	setAttributeValue("def21", newDef21);
	} 	  
	/**
	 * 属性def22的Getter方法.属性名：自定义项22
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef22 () {
		return (java.lang.String)getAttributeValue("def22");
	}   
	/**
	 * 属性def22的Setter方法.属性名：自定义项22
	 * 创建日期:
	 * @param newDef22 java.lang.String
	 */
	public void setDef22 (java.lang.String newDef22 ) {
	 	setAttributeValue("def22", newDef22);
	} 	  
	/**
	 * 属性def23的Getter方法.属性名：自定义项23
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef23 () {
		return (java.lang.String)getAttributeValue("def23");
	}   
	/**
	 * 属性def23的Setter方法.属性名：自定义项23
	 * 创建日期:
	 * @param newDef23 java.lang.String
	 */
	public void setDef23 (java.lang.String newDef23 ) {
	 	setAttributeValue("def23", newDef23);
	} 	  
	/**
	 * 属性def24的Getter方法.属性名：自定义项24
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef24 () {
		return (java.lang.String)getAttributeValue("def24");
	}   
	/**
	 * 属性def24的Setter方法.属性名：自定义项24
	 * 创建日期:
	 * @param newDef24 java.lang.String
	 */
	public void setDef24 (java.lang.String newDef24 ) {
	 	setAttributeValue("def24", newDef24);
	} 	  
	/**
	 * 属性def25的Getter方法.属性名：自定义项25
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef25 () {
		return (java.lang.String)getAttributeValue("def25");
	}   
	/**
	 * 属性def25的Setter方法.属性名：自定义项25
	 * 创建日期:
	 * @param newDef25 java.lang.String
	 */
	public void setDef25 (java.lang.String newDef25 ) {
	 	setAttributeValue("def25", newDef25);
	} 	  
	/**
	 * 属性def26的Getter方法.属性名：自定义项26
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef26 () {
		return (java.lang.String)getAttributeValue("def26");
	}   
	/**
	 * 属性def26的Setter方法.属性名：自定义项26
	 * 创建日期:
	 * @param newDef26 java.lang.String
	 */
	public void setDef26 (java.lang.String newDef26 ) {
	 	setAttributeValue("def26", newDef26);
	} 	  
	/**
	 * 属性def27的Getter方法.属性名：自定义项27
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef27 () {
		return (java.lang.String)getAttributeValue("def27");
	}   
	/**
	 * 属性def27的Setter方法.属性名：自定义项27
	 * 创建日期:
	 * @param newDef27 java.lang.String
	 */
	public void setDef27 (java.lang.String newDef27 ) {
	 	setAttributeValue("def27", newDef27);
	} 	  
	/**
	 * 属性def28的Getter方法.属性名：自定义项28
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef28 () {
		return (java.lang.String)getAttributeValue("def28");
	}   
	/**
	 * 属性def28的Setter方法.属性名：自定义项28
	 * 创建日期:
	 * @param newDef28 java.lang.String
	 */
	public void setDef28 (java.lang.String newDef28 ) {
	 	setAttributeValue("def28", newDef28);
	} 	  
	/**
	 * 属性def29的Getter方法.属性名：自定义项29
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef29 () {
		return (java.lang.String)getAttributeValue("def29");
	}   
	/**
	 * 属性def29的Setter方法.属性名：自定义项29
	 * 创建日期:
	 * @param newDef29 java.lang.String
	 */
	public void setDef29 (java.lang.String newDef29 ) {
	 	setAttributeValue("def29", newDef29);
	} 	  
	/**
	 * 属性def30的Getter方法.属性名：自定义项30
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDef30 () {
		return (java.lang.String)getAttributeValue("def30");
	}   
	/**
	 * 属性def30的Setter方法.属性名：自定义项30
	 * 创建日期:
	 * @param newDef30 java.lang.String
	 */
	public void setDef30 (java.lang.String newDef30 ) {
	 	setAttributeValue("def30", newDef30);
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return (java.lang.Integer)getAttributeValue("dr");
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	setAttributeValue("dr", newDr);
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return (nc.vo.pub.lang.UFDateTime)getAttributeValue("ts");
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	setAttributeValue("ts", newTs);
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_builds";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "phm_mbuilds";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public MbuildsHeadVO() {
		super();	
	}  
	
	public IVOMeta getMetaData() {
    	IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("phm.mbuilds");
   		return meta;
  	}
} 
